###################################################################

# Created by write_sdc on Tue Dec  6 23:07:17 2022

###################################################################
set sdc_version 2.0

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_area 0
set_load -pin_load 0.2 [get_ports {v_out[15]}]
set_load -pin_load 0.2 [get_ports {v_out[14]}]
set_load -pin_load 0.2 [get_ports {v_out[13]}]
set_load -pin_load 0.2 [get_ports {v_out[12]}]
set_load -pin_load 0.2 [get_ports {v_out[11]}]
set_load -pin_load 0.2 [get_ports {v_out[10]}]
set_load -pin_load 0.2 [get_ports {v_out[9]}]
set_load -pin_load 0.2 [get_ports {v_out[8]}]
set_load -pin_load 0.2 [get_ports {v_out[7]}]
set_load -pin_load 0.2 [get_ports {v_out[6]}]
set_load -pin_load 0.2 [get_ports {v_out[5]}]
set_load -pin_load 0.2 [get_ports {v_out[4]}]
set_load -pin_load 0.2 [get_ports {v_out[3]}]
set_load -pin_load 0.2 [get_ports {v_out[2]}]
set_load -pin_load 0.2 [get_ports {v_out[1]}]
set_load -pin_load 0.2 [get_ports {v_out[0]}]
set_load -pin_load 0.2 [get_ports datavaild_o]
set_load -pin_load 0.2 [get_ports {x_out[127]}]
set_load -pin_load 0.2 [get_ports {x_out[126]}]
set_load -pin_load 0.2 [get_ports {x_out[125]}]
set_load -pin_load 0.2 [get_ports {x_out[124]}]
set_load -pin_load 0.2 [get_ports {x_out[123]}]
set_load -pin_load 0.2 [get_ports {x_out[122]}]
set_load -pin_load 0.2 [get_ports {x_out[121]}]
set_load -pin_load 0.2 [get_ports {x_out[120]}]
set_load -pin_load 0.2 [get_ports {x_out[119]}]
set_load -pin_load 0.2 [get_ports {x_out[118]}]
set_load -pin_load 0.2 [get_ports {x_out[117]}]
set_load -pin_load 0.2 [get_ports {x_out[116]}]
set_load -pin_load 0.2 [get_ports {x_out[115]}]
set_load -pin_load 0.2 [get_ports {x_out[114]}]
set_load -pin_load 0.2 [get_ports {x_out[113]}]
set_load -pin_load 0.2 [get_ports {x_out[112]}]
set_load -pin_load 0.2 [get_ports {x_out[111]}]
set_load -pin_load 0.2 [get_ports {x_out[110]}]
set_load -pin_load 0.2 [get_ports {x_out[109]}]
set_load -pin_load 0.2 [get_ports {x_out[108]}]
set_load -pin_load 0.2 [get_ports {x_out[107]}]
set_load -pin_load 0.2 [get_ports {x_out[106]}]
set_load -pin_load 0.2 [get_ports {x_out[105]}]
set_load -pin_load 0.2 [get_ports {x_out[104]}]
set_load -pin_load 0.2 [get_ports {x_out[103]}]
set_load -pin_load 0.2 [get_ports {x_out[102]}]
set_load -pin_load 0.2 [get_ports {x_out[101]}]
set_load -pin_load 0.2 [get_ports {x_out[100]}]
set_load -pin_load 0.2 [get_ports {x_out[99]}]
set_load -pin_load 0.2 [get_ports {x_out[98]}]
set_load -pin_load 0.2 [get_ports {x_out[97]}]
set_load -pin_load 0.2 [get_ports {x_out[96]}]
set_load -pin_load 0.2 [get_ports {x_out[95]}]
set_load -pin_load 0.2 [get_ports {x_out[94]}]
set_load -pin_load 0.2 [get_ports {x_out[93]}]
set_load -pin_load 0.2 [get_ports {x_out[92]}]
set_load -pin_load 0.2 [get_ports {x_out[91]}]
set_load -pin_load 0.2 [get_ports {x_out[90]}]
set_load -pin_load 0.2 [get_ports {x_out[89]}]
set_load -pin_load 0.2 [get_ports {x_out[88]}]
set_load -pin_load 0.2 [get_ports {x_out[87]}]
set_load -pin_load 0.2 [get_ports {x_out[86]}]
set_load -pin_load 0.2 [get_ports {x_out[85]}]
set_load -pin_load 0.2 [get_ports {x_out[84]}]
set_load -pin_load 0.2 [get_ports {x_out[83]}]
set_load -pin_load 0.2 [get_ports {x_out[82]}]
set_load -pin_load 0.2 [get_ports {x_out[81]}]
set_load -pin_load 0.2 [get_ports {x_out[80]}]
set_load -pin_load 0.2 [get_ports {x_out[79]}]
set_load -pin_load 0.2 [get_ports {x_out[78]}]
set_load -pin_load 0.2 [get_ports {x_out[77]}]
set_load -pin_load 0.2 [get_ports {x_out[76]}]
set_load -pin_load 0.2 [get_ports {x_out[75]}]
set_load -pin_load 0.2 [get_ports {x_out[74]}]
set_load -pin_load 0.2 [get_ports {x_out[73]}]
set_load -pin_load 0.2 [get_ports {x_out[72]}]
set_load -pin_load 0.2 [get_ports {x_out[71]}]
set_load -pin_load 0.2 [get_ports {x_out[70]}]
set_load -pin_load 0.2 [get_ports {x_out[69]}]
set_load -pin_load 0.2 [get_ports {x_out[68]}]
set_load -pin_load 0.2 [get_ports {x_out[67]}]
set_load -pin_load 0.2 [get_ports {x_out[66]}]
set_load -pin_load 0.2 [get_ports {x_out[65]}]
set_load -pin_load 0.2 [get_ports {x_out[64]}]
set_load -pin_load 0.2 [get_ports {x_out[63]}]
set_load -pin_load 0.2 [get_ports {x_out[62]}]
set_load -pin_load 0.2 [get_ports {x_out[61]}]
set_load -pin_load 0.2 [get_ports {x_out[60]}]
set_load -pin_load 0.2 [get_ports {x_out[59]}]
set_load -pin_load 0.2 [get_ports {x_out[58]}]
set_load -pin_load 0.2 [get_ports {x_out[57]}]
set_load -pin_load 0.2 [get_ports {x_out[56]}]
set_load -pin_load 0.2 [get_ports {x_out[55]}]
set_load -pin_load 0.2 [get_ports {x_out[54]}]
set_load -pin_load 0.2 [get_ports {x_out[53]}]
set_load -pin_load 0.2 [get_ports {x_out[52]}]
set_load -pin_load 0.2 [get_ports {x_out[51]}]
set_load -pin_load 0.2 [get_ports {x_out[50]}]
set_load -pin_load 0.2 [get_ports {x_out[49]}]
set_load -pin_load 0.2 [get_ports {x_out[48]}]
set_load -pin_load 0.2 [get_ports {x_out[47]}]
set_load -pin_load 0.2 [get_ports {x_out[46]}]
set_load -pin_load 0.2 [get_ports {x_out[45]}]
set_load -pin_load 0.2 [get_ports {x_out[44]}]
set_load -pin_load 0.2 [get_ports {x_out[43]}]
set_load -pin_load 0.2 [get_ports {x_out[42]}]
set_load -pin_load 0.2 [get_ports {x_out[41]}]
set_load -pin_load 0.2 [get_ports {x_out[40]}]
set_load -pin_load 0.2 [get_ports {x_out[39]}]
set_load -pin_load 0.2 [get_ports {x_out[38]}]
set_load -pin_load 0.2 [get_ports {x_out[37]}]
set_load -pin_load 0.2 [get_ports {x_out[36]}]
set_load -pin_load 0.2 [get_ports {x_out[35]}]
set_load -pin_load 0.2 [get_ports {x_out[34]}]
set_load -pin_load 0.2 [get_ports {x_out[33]}]
set_load -pin_load 0.2 [get_ports {x_out[32]}]
set_load -pin_load 0.2 [get_ports {x_out[31]}]
set_load -pin_load 0.2 [get_ports {x_out[30]}]
set_load -pin_load 0.2 [get_ports {x_out[29]}]
set_load -pin_load 0.2 [get_ports {x_out[28]}]
set_load -pin_load 0.2 [get_ports {x_out[27]}]
set_load -pin_load 0.2 [get_ports {x_out[26]}]
set_load -pin_load 0.2 [get_ports {x_out[25]}]
set_load -pin_load 0.2 [get_ports {x_out[24]}]
set_load -pin_load 0.2 [get_ports {x_out[23]}]
set_load -pin_load 0.2 [get_ports {x_out[22]}]
set_load -pin_load 0.2 [get_ports {x_out[21]}]
set_load -pin_load 0.2 [get_ports {x_out[20]}]
set_load -pin_load 0.2 [get_ports {x_out[19]}]
set_load -pin_load 0.2 [get_ports {x_out[18]}]
set_load -pin_load 0.2 [get_ports {x_out[17]}]
set_load -pin_load 0.2 [get_ports {x_out[16]}]
set_load -pin_load 0.2 [get_ports {x_out[15]}]
set_load -pin_load 0.2 [get_ports {x_out[14]}]
set_load -pin_load 0.2 [get_ports {x_out[13]}]
set_load -pin_load 0.2 [get_ports {x_out[12]}]
set_load -pin_load 0.2 [get_ports {x_out[11]}]
set_load -pin_load 0.2 [get_ports {x_out[10]}]
set_load -pin_load 0.2 [get_ports {x_out[9]}]
set_load -pin_load 0.2 [get_ports {x_out[8]}]
set_load -pin_load 0.2 [get_ports {x_out[7]}]
set_load -pin_load 0.2 [get_ports {x_out[6]}]
set_load -pin_load 0.2 [get_ports {x_out[5]}]
set_load -pin_load 0.2 [get_ports {x_out[4]}]
set_load -pin_load 0.2 [get_ports {x_out[3]}]
set_load -pin_load 0.2 [get_ports {x_out[2]}]
set_load -pin_load 0.2 [get_ports {x_out[1]}]
set_load -pin_load 0.2 [get_ports {x_out[0]}]
set_ideal_network -no_propagate  [get_ports rst_n]
create_clock [get_ports clk]  -period 9.5  -waveform {0 4.75}
set_clock_latency -max 0.95  [get_clocks clk]
set_clock_latency -source 0.95  [get_clocks clk]
set_clock_uncertainty 0.475  [get_clocks clk]
set_clock_transition -max -rise 0.095 [get_clocks clk]
set_clock_transition -max -fall 0.095 [get_clocks clk]
set_clock_transition -min -rise 0.095 [get_clocks clk]
set_clock_transition -min -fall 0.095 [get_clocks clk]
set_false_path   -from [get_ports rst_n]
set_input_delay -clock clk  -max 3.8  [get_ports rst_n]
set_input_delay -clock clk  -min 0  [get_ports rst_n]
set_input_delay -clock clk  -max 3.8  [get_ports vaild_i]
set_input_delay -clock clk  -min 0  [get_ports vaild_i]
set_input_delay -clock clk  -max 3.8  [get_ports {v_in[15]}]
set_input_delay -clock clk  -min 0  [get_ports {v_in[15]}]
set_input_delay -clock clk  -max 3.8  [get_ports {v_in[14]}]
set_input_delay -clock clk  -min 0  [get_ports {v_in[14]}]
set_input_delay -clock clk  -max 3.8  [get_ports {v_in[13]}]
set_input_delay -clock clk  -min 0  [get_ports {v_in[13]}]
set_input_delay -clock clk  -max 3.8  [get_ports {v_in[12]}]
set_input_delay -clock clk  -min 0  [get_ports {v_in[12]}]
set_input_delay -clock clk  -max 3.8  [get_ports {v_in[11]}]
set_input_delay -clock clk  -min 0  [get_ports {v_in[11]}]
set_input_delay -clock clk  -max 3.8  [get_ports {v_in[10]}]
set_input_delay -clock clk  -min 0  [get_ports {v_in[10]}]
set_input_delay -clock clk  -max 3.8  [get_ports {v_in[9]}]
set_input_delay -clock clk  -min 0  [get_ports {v_in[9]}]
set_input_delay -clock clk  -max 3.8  [get_ports {v_in[8]}]
set_input_delay -clock clk  -min 0  [get_ports {v_in[8]}]
set_input_delay -clock clk  -max 3.8  [get_ports {v_in[7]}]
set_input_delay -clock clk  -min 0  [get_ports {v_in[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {v_in[6]}]
set_input_delay -clock clk  -min 0  [get_ports {v_in[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {v_in[5]}]
set_input_delay -clock clk  -min 0  [get_ports {v_in[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {v_in[4]}]
set_input_delay -clock clk  -min 0  [get_ports {v_in[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {v_in[3]}]
set_input_delay -clock clk  -min 0  [get_ports {v_in[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {v_in[2]}]
set_input_delay -clock clk  -min 0  [get_ports {v_in[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {v_in[1]}]
set_input_delay -clock clk  -min 0  [get_ports {v_in[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {v_in[0]}]
set_input_delay -clock clk  -min 0  [get_ports {v_in[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[127]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[127]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[126]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[126]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[125]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[125]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[124]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[124]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[123]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[123]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[122]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[122]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[121]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[121]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[120]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[120]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[119]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[119]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[118]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[118]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[117]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[117]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[116]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[116]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[115]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[115]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[114]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[114]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[113]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[113]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[112]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[112]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[111]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[111]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[110]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[110]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[109]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[109]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[108]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[108]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[107]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[107]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[106]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[106]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[105]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[105]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[104]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[104]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[103]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[103]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[102]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[102]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[101]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[101]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[100]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[100]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[99]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[99]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[98]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[98]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[97]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[97]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[96]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[96]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[95]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[95]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[94]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[94]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[93]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[93]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[92]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[92]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[91]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[91]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[90]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[90]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[89]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[89]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[88]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[88]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[87]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[87]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[86]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[86]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[85]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[85]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[84]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[84]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[83]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[83]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[82]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[82]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[81]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[81]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[80]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[80]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[79]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[79]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[78]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[78]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[77]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[77]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[76]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[76]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[75]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[75]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[74]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[74]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[73]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[73]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[72]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[72]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[71]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[71]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[70]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[70]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[69]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[69]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[68]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[68]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[67]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[67]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[66]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[66]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[65]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[65]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[64]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[64]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[63]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[63]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[62]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[62]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[61]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[61]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[60]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[60]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[59]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[59]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[58]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[58]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[57]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[57]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[56]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[56]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[55]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[55]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[54]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[54]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[53]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[53]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[52]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[52]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[51]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[51]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[50]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[50]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[49]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[49]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[48]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[48]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[47]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[47]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[46]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[46]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[45]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[45]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[44]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[44]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[43]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[43]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[42]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[42]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[41]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[41]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[40]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[40]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[39]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[39]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[38]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[38]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[37]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[37]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[36]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[36]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[35]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[35]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[34]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[34]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[33]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[33]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[32]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[32]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[31]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[31]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[30]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[30]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[29]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[29]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[28]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[28]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[27]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[27]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[26]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[26]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[25]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[25]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[24]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[24]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[23]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[23]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[22]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[22]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[21]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[21]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[20]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[20]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[19]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[19]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[18]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[18]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[17]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[17]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[16]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[16]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[15]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[15]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[14]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[14]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[13]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[13]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[12]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[12]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[11]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[11]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[10]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[10]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[9]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[9]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[8]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[8]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[7]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[6]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[5]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[4]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[3]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[2]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[1]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {x_in[0]}]
set_input_delay -clock clk  -min 0  [get_ports {x_in[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {v_out[15]}]
set_output_delay -clock clk  -min 0  [get_ports {v_out[15]}]
set_output_delay -clock clk  -max 3.8  [get_ports {v_out[14]}]
set_output_delay -clock clk  -min 0  [get_ports {v_out[14]}]
set_output_delay -clock clk  -max 3.8  [get_ports {v_out[13]}]
set_output_delay -clock clk  -min 0  [get_ports {v_out[13]}]
set_output_delay -clock clk  -max 3.8  [get_ports {v_out[12]}]
set_output_delay -clock clk  -min 0  [get_ports {v_out[12]}]
set_output_delay -clock clk  -max 3.8  [get_ports {v_out[11]}]
set_output_delay -clock clk  -min 0  [get_ports {v_out[11]}]
set_output_delay -clock clk  -max 3.8  [get_ports {v_out[10]}]
set_output_delay -clock clk  -min 0  [get_ports {v_out[10]}]
set_output_delay -clock clk  -max 3.8  [get_ports {v_out[9]}]
set_output_delay -clock clk  -min 0  [get_ports {v_out[9]}]
set_output_delay -clock clk  -max 3.8  [get_ports {v_out[8]}]
set_output_delay -clock clk  -min 0  [get_ports {v_out[8]}]
set_output_delay -clock clk  -max 3.8  [get_ports {v_out[7]}]
set_output_delay -clock clk  -min 0  [get_ports {v_out[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {v_out[6]}]
set_output_delay -clock clk  -min 0  [get_ports {v_out[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {v_out[5]}]
set_output_delay -clock clk  -min 0  [get_ports {v_out[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {v_out[4]}]
set_output_delay -clock clk  -min 0  [get_ports {v_out[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {v_out[3]}]
set_output_delay -clock clk  -min 0  [get_ports {v_out[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {v_out[2]}]
set_output_delay -clock clk  -min 0  [get_ports {v_out[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {v_out[1]}]
set_output_delay -clock clk  -min 0  [get_ports {v_out[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {v_out[0]}]
set_output_delay -clock clk  -min 0  [get_ports {v_out[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports datavaild_o]
set_output_delay -clock clk  -min 0  [get_ports datavaild_o]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[127]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[127]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[126]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[126]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[125]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[125]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[124]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[124]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[123]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[123]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[122]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[122]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[121]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[121]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[120]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[120]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[119]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[119]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[118]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[118]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[117]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[117]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[116]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[116]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[115]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[115]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[114]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[114]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[113]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[113]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[112]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[112]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[111]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[111]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[110]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[110]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[109]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[109]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[108]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[108]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[107]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[107]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[106]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[106]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[105]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[105]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[104]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[104]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[103]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[103]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[102]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[102]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[101]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[101]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[100]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[100]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[99]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[99]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[98]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[98]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[97]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[97]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[96]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[96]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[95]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[95]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[94]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[94]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[93]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[93]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[92]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[92]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[91]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[91]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[90]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[90]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[89]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[89]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[88]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[88]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[87]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[87]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[86]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[86]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[85]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[85]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[84]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[84]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[83]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[83]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[82]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[82]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[81]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[81]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[80]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[80]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[79]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[79]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[78]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[78]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[77]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[77]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[76]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[76]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[75]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[75]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[74]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[74]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[73]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[73]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[72]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[72]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[71]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[71]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[70]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[70]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[69]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[69]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[68]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[68]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[67]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[67]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[66]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[66]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[65]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[65]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[64]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[64]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[63]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[63]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[62]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[62]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[61]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[61]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[60]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[60]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[59]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[59]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[58]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[58]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[57]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[57]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[56]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[56]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[55]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[55]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[54]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[54]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[53]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[53]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[52]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[52]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[51]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[51]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[50]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[50]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[49]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[49]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[48]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[48]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[47]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[47]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[46]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[46]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[45]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[45]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[44]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[44]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[43]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[43]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[42]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[42]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[41]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[41]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[40]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[40]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[39]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[39]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[38]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[38]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[37]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[37]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[36]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[36]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[35]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[35]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[34]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[34]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[33]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[33]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[32]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[32]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[31]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[31]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[30]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[30]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[29]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[29]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[28]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[28]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[27]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[27]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[26]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[26]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[25]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[25]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[24]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[24]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[23]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[23]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[22]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[22]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[21]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[21]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[20]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[20]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[19]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[19]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[18]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[18]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[17]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[17]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[16]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[16]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[15]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[15]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[14]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[14]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[13]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[13]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[12]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[12]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[11]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[11]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[10]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[10]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[9]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[9]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[8]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[8]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[7]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[6]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[5]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[4]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[3]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[2]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[1]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {x_out[0]}]
set_output_delay -clock clk  -min 0  [get_ports {x_out[0]}]
