###################################################################

# Created by write_sdc on Sun Nov 13 17:30:11 2022

###################################################################
set sdc_version 2.0

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_area 0
set_load -pin_load 0.2 [get_ports vld_out]
set_load -pin_load 0.2 [get_ports {dout_0[7]}]
set_load -pin_load 0.2 [get_ports {dout_0[6]}]
set_load -pin_load 0.2 [get_ports {dout_0[5]}]
set_load -pin_load 0.2 [get_ports {dout_0[4]}]
set_load -pin_load 0.2 [get_ports {dout_0[3]}]
set_load -pin_load 0.2 [get_ports {dout_0[2]}]
set_load -pin_load 0.2 [get_ports {dout_0[1]}]
set_load -pin_load 0.2 [get_ports {dout_0[0]}]
set_load -pin_load 0.2 [get_ports {dout_1[7]}]
set_load -pin_load 0.2 [get_ports {dout_1[6]}]
set_load -pin_load 0.2 [get_ports {dout_1[5]}]
set_load -pin_load 0.2 [get_ports {dout_1[4]}]
set_load -pin_load 0.2 [get_ports {dout_1[3]}]
set_load -pin_load 0.2 [get_ports {dout_1[2]}]
set_load -pin_load 0.2 [get_ports {dout_1[1]}]
set_load -pin_load 0.2 [get_ports {dout_1[0]}]
set_load -pin_load 0.2 [get_ports {dout_2[7]}]
set_load -pin_load 0.2 [get_ports {dout_2[6]}]
set_load -pin_load 0.2 [get_ports {dout_2[5]}]
set_load -pin_load 0.2 [get_ports {dout_2[4]}]
set_load -pin_load 0.2 [get_ports {dout_2[3]}]
set_load -pin_load 0.2 [get_ports {dout_2[2]}]
set_load -pin_load 0.2 [get_ports {dout_2[1]}]
set_load -pin_load 0.2 [get_ports {dout_2[0]}]
set_load -pin_load 0.2 [get_ports {dout_3[7]}]
set_load -pin_load 0.2 [get_ports {dout_3[6]}]
set_load -pin_load 0.2 [get_ports {dout_3[5]}]
set_load -pin_load 0.2 [get_ports {dout_3[4]}]
set_load -pin_load 0.2 [get_ports {dout_3[3]}]
set_load -pin_load 0.2 [get_ports {dout_3[2]}]
set_load -pin_load 0.2 [get_ports {dout_3[1]}]
set_load -pin_load 0.2 [get_ports {dout_3[0]}]
set_load -pin_load 0.2 [get_ports {dout_4[7]}]
set_load -pin_load 0.2 [get_ports {dout_4[6]}]
set_load -pin_load 0.2 [get_ports {dout_4[5]}]
set_load -pin_load 0.2 [get_ports {dout_4[4]}]
set_load -pin_load 0.2 [get_ports {dout_4[3]}]
set_load -pin_load 0.2 [get_ports {dout_4[2]}]
set_load -pin_load 0.2 [get_ports {dout_4[1]}]
set_load -pin_load 0.2 [get_ports {dout_4[0]}]
set_load -pin_load 0.2 [get_ports {dout_5[7]}]
set_load -pin_load 0.2 [get_ports {dout_5[6]}]
set_load -pin_load 0.2 [get_ports {dout_5[5]}]
set_load -pin_load 0.2 [get_ports {dout_5[4]}]
set_load -pin_load 0.2 [get_ports {dout_5[3]}]
set_load -pin_load 0.2 [get_ports {dout_5[2]}]
set_load -pin_load 0.2 [get_ports {dout_5[1]}]
set_load -pin_load 0.2 [get_ports {dout_5[0]}]
set_load -pin_load 0.2 [get_ports {dout_6[7]}]
set_load -pin_load 0.2 [get_ports {dout_6[6]}]
set_load -pin_load 0.2 [get_ports {dout_6[5]}]
set_load -pin_load 0.2 [get_ports {dout_6[4]}]
set_load -pin_load 0.2 [get_ports {dout_6[3]}]
set_load -pin_load 0.2 [get_ports {dout_6[2]}]
set_load -pin_load 0.2 [get_ports {dout_6[1]}]
set_load -pin_load 0.2 [get_ports {dout_6[0]}]
set_load -pin_load 0.2 [get_ports {dout_7[7]}]
set_load -pin_load 0.2 [get_ports {dout_7[6]}]
set_load -pin_load 0.2 [get_ports {dout_7[5]}]
set_load -pin_load 0.2 [get_ports {dout_7[4]}]
set_load -pin_load 0.2 [get_ports {dout_7[3]}]
set_load -pin_load 0.2 [get_ports {dout_7[2]}]
set_load -pin_load 0.2 [get_ports {dout_7[1]}]
set_load -pin_load 0.2 [get_ports {dout_7[0]}]
set_load -pin_load 0.2 [get_ports {dout_8[7]}]
set_load -pin_load 0.2 [get_ports {dout_8[6]}]
set_load -pin_load 0.2 [get_ports {dout_8[5]}]
set_load -pin_load 0.2 [get_ports {dout_8[4]}]
set_load -pin_load 0.2 [get_ports {dout_8[3]}]
set_load -pin_load 0.2 [get_ports {dout_8[2]}]
set_load -pin_load 0.2 [get_ports {dout_8[1]}]
set_load -pin_load 0.2 [get_ports {dout_8[0]}]
set_load -pin_load 0.2 [get_ports {dout_9[7]}]
set_load -pin_load 0.2 [get_ports {dout_9[6]}]
set_load -pin_load 0.2 [get_ports {dout_9[5]}]
set_load -pin_load 0.2 [get_ports {dout_9[4]}]
set_load -pin_load 0.2 [get_ports {dout_9[3]}]
set_load -pin_load 0.2 [get_ports {dout_9[2]}]
set_load -pin_load 0.2 [get_ports {dout_9[1]}]
set_load -pin_load 0.2 [get_ports {dout_9[0]}]
set_load -pin_load 0.2 [get_ports {dout_10[7]}]
set_load -pin_load 0.2 [get_ports {dout_10[6]}]
set_load -pin_load 0.2 [get_ports {dout_10[5]}]
set_load -pin_load 0.2 [get_ports {dout_10[4]}]
set_load -pin_load 0.2 [get_ports {dout_10[3]}]
set_load -pin_load 0.2 [get_ports {dout_10[2]}]
set_load -pin_load 0.2 [get_ports {dout_10[1]}]
set_load -pin_load 0.2 [get_ports {dout_10[0]}]
set_load -pin_load 0.2 [get_ports {dout_11[7]}]
set_load -pin_load 0.2 [get_ports {dout_11[6]}]
set_load -pin_load 0.2 [get_ports {dout_11[5]}]
set_load -pin_load 0.2 [get_ports {dout_11[4]}]
set_load -pin_load 0.2 [get_ports {dout_11[3]}]
set_load -pin_load 0.2 [get_ports {dout_11[2]}]
set_load -pin_load 0.2 [get_ports {dout_11[1]}]
set_load -pin_load 0.2 [get_ports {dout_11[0]}]
set_load -pin_load 0.2 [get_ports {dout_12[7]}]
set_load -pin_load 0.2 [get_ports {dout_12[6]}]
set_load -pin_load 0.2 [get_ports {dout_12[5]}]
set_load -pin_load 0.2 [get_ports {dout_12[4]}]
set_load -pin_load 0.2 [get_ports {dout_12[3]}]
set_load -pin_load 0.2 [get_ports {dout_12[2]}]
set_load -pin_load 0.2 [get_ports {dout_12[1]}]
set_load -pin_load 0.2 [get_ports {dout_12[0]}]
set_load -pin_load 0.2 [get_ports {dout_13[7]}]
set_load -pin_load 0.2 [get_ports {dout_13[6]}]
set_load -pin_load 0.2 [get_ports {dout_13[5]}]
set_load -pin_load 0.2 [get_ports {dout_13[4]}]
set_load -pin_load 0.2 [get_ports {dout_13[3]}]
set_load -pin_load 0.2 [get_ports {dout_13[2]}]
set_load -pin_load 0.2 [get_ports {dout_13[1]}]
set_load -pin_load 0.2 [get_ports {dout_13[0]}]
set_load -pin_load 0.2 [get_ports {dout_14[7]}]
set_load -pin_load 0.2 [get_ports {dout_14[6]}]
set_load -pin_load 0.2 [get_ports {dout_14[5]}]
set_load -pin_load 0.2 [get_ports {dout_14[4]}]
set_load -pin_load 0.2 [get_ports {dout_14[3]}]
set_load -pin_load 0.2 [get_ports {dout_14[2]}]
set_load -pin_load 0.2 [get_ports {dout_14[1]}]
set_load -pin_load 0.2 [get_ports {dout_14[0]}]
set_load -pin_load 0.2 [get_ports {dout_15[7]}]
set_load -pin_load 0.2 [get_ports {dout_15[6]}]
set_load -pin_load 0.2 [get_ports {dout_15[5]}]
set_load -pin_load 0.2 [get_ports {dout_15[4]}]
set_load -pin_load 0.2 [get_ports {dout_15[3]}]
set_load -pin_load 0.2 [get_ports {dout_15[2]}]
set_load -pin_load 0.2 [get_ports {dout_15[1]}]
set_load -pin_load 0.2 [get_ports {dout_15[0]}]
set_load -pin_load 0.2 [get_ports {dout_16[7]}]
set_load -pin_load 0.2 [get_ports {dout_16[6]}]
set_load -pin_load 0.2 [get_ports {dout_16[5]}]
set_load -pin_load 0.2 [get_ports {dout_16[4]}]
set_load -pin_load 0.2 [get_ports {dout_16[3]}]
set_load -pin_load 0.2 [get_ports {dout_16[2]}]
set_load -pin_load 0.2 [get_ports {dout_16[1]}]
set_load -pin_load 0.2 [get_ports {dout_16[0]}]
set_load -pin_load 0.2 [get_ports {dout_17[7]}]
set_load -pin_load 0.2 [get_ports {dout_17[6]}]
set_load -pin_load 0.2 [get_ports {dout_17[5]}]
set_load -pin_load 0.2 [get_ports {dout_17[4]}]
set_load -pin_load 0.2 [get_ports {dout_17[3]}]
set_load -pin_load 0.2 [get_ports {dout_17[2]}]
set_load -pin_load 0.2 [get_ports {dout_17[1]}]
set_load -pin_load 0.2 [get_ports {dout_17[0]}]
set_load -pin_load 0.2 [get_ports {dout_18[7]}]
set_load -pin_load 0.2 [get_ports {dout_18[6]}]
set_load -pin_load 0.2 [get_ports {dout_18[5]}]
set_load -pin_load 0.2 [get_ports {dout_18[4]}]
set_load -pin_load 0.2 [get_ports {dout_18[3]}]
set_load -pin_load 0.2 [get_ports {dout_18[2]}]
set_load -pin_load 0.2 [get_ports {dout_18[1]}]
set_load -pin_load 0.2 [get_ports {dout_18[0]}]
set_load -pin_load 0.2 [get_ports {dout_19[7]}]
set_load -pin_load 0.2 [get_ports {dout_19[6]}]
set_load -pin_load 0.2 [get_ports {dout_19[5]}]
set_load -pin_load 0.2 [get_ports {dout_19[4]}]
set_load -pin_load 0.2 [get_ports {dout_19[3]}]
set_load -pin_load 0.2 [get_ports {dout_19[2]}]
set_load -pin_load 0.2 [get_ports {dout_19[1]}]
set_load -pin_load 0.2 [get_ports {dout_19[0]}]
set_load -pin_load 0.2 [get_ports {dout_20[7]}]
set_load -pin_load 0.2 [get_ports {dout_20[6]}]
set_load -pin_load 0.2 [get_ports {dout_20[5]}]
set_load -pin_load 0.2 [get_ports {dout_20[4]}]
set_load -pin_load 0.2 [get_ports {dout_20[3]}]
set_load -pin_load 0.2 [get_ports {dout_20[2]}]
set_load -pin_load 0.2 [get_ports {dout_20[1]}]
set_load -pin_load 0.2 [get_ports {dout_20[0]}]
set_load -pin_load 0.2 [get_ports {dout_21[7]}]
set_load -pin_load 0.2 [get_ports {dout_21[6]}]
set_load -pin_load 0.2 [get_ports {dout_21[5]}]
set_load -pin_load 0.2 [get_ports {dout_21[4]}]
set_load -pin_load 0.2 [get_ports {dout_21[3]}]
set_load -pin_load 0.2 [get_ports {dout_21[2]}]
set_load -pin_load 0.2 [get_ports {dout_21[1]}]
set_load -pin_load 0.2 [get_ports {dout_21[0]}]
set_load -pin_load 0.2 [get_ports {dout_22[7]}]
set_load -pin_load 0.2 [get_ports {dout_22[6]}]
set_load -pin_load 0.2 [get_ports {dout_22[5]}]
set_load -pin_load 0.2 [get_ports {dout_22[4]}]
set_load -pin_load 0.2 [get_ports {dout_22[3]}]
set_load -pin_load 0.2 [get_ports {dout_22[2]}]
set_load -pin_load 0.2 [get_ports {dout_22[1]}]
set_load -pin_load 0.2 [get_ports {dout_22[0]}]
set_load -pin_load 0.2 [get_ports {dout_23[7]}]
set_load -pin_load 0.2 [get_ports {dout_23[6]}]
set_load -pin_load 0.2 [get_ports {dout_23[5]}]
set_load -pin_load 0.2 [get_ports {dout_23[4]}]
set_load -pin_load 0.2 [get_ports {dout_23[3]}]
set_load -pin_load 0.2 [get_ports {dout_23[2]}]
set_load -pin_load 0.2 [get_ports {dout_23[1]}]
set_load -pin_load 0.2 [get_ports {dout_23[0]}]
set_load -pin_load 0.2 [get_ports {dout_24[7]}]
set_load -pin_load 0.2 [get_ports {dout_24[6]}]
set_load -pin_load 0.2 [get_ports {dout_24[5]}]
set_load -pin_load 0.2 [get_ports {dout_24[4]}]
set_load -pin_load 0.2 [get_ports {dout_24[3]}]
set_load -pin_load 0.2 [get_ports {dout_24[2]}]
set_load -pin_load 0.2 [get_ports {dout_24[1]}]
set_load -pin_load 0.2 [get_ports {dout_24[0]}]
set_load -pin_load 0.2 [get_ports {dout_25[7]}]
set_load -pin_load 0.2 [get_ports {dout_25[6]}]
set_load -pin_load 0.2 [get_ports {dout_25[5]}]
set_load -pin_load 0.2 [get_ports {dout_25[4]}]
set_load -pin_load 0.2 [get_ports {dout_25[3]}]
set_load -pin_load 0.2 [get_ports {dout_25[2]}]
set_load -pin_load 0.2 [get_ports {dout_25[1]}]
set_load -pin_load 0.2 [get_ports {dout_25[0]}]
set_load -pin_load 0.2 [get_ports {dout_26[7]}]
set_load -pin_load 0.2 [get_ports {dout_26[6]}]
set_load -pin_load 0.2 [get_ports {dout_26[5]}]
set_load -pin_load 0.2 [get_ports {dout_26[4]}]
set_load -pin_load 0.2 [get_ports {dout_26[3]}]
set_load -pin_load 0.2 [get_ports {dout_26[2]}]
set_load -pin_load 0.2 [get_ports {dout_26[1]}]
set_load -pin_load 0.2 [get_ports {dout_26[0]}]
set_load -pin_load 0.2 [get_ports {dout_27[7]}]
set_load -pin_load 0.2 [get_ports {dout_27[6]}]
set_load -pin_load 0.2 [get_ports {dout_27[5]}]
set_load -pin_load 0.2 [get_ports {dout_27[4]}]
set_load -pin_load 0.2 [get_ports {dout_27[3]}]
set_load -pin_load 0.2 [get_ports {dout_27[2]}]
set_load -pin_load 0.2 [get_ports {dout_27[1]}]
set_load -pin_load 0.2 [get_ports {dout_27[0]}]
set_load -pin_load 0.2 [get_ports {dout_28[7]}]
set_load -pin_load 0.2 [get_ports {dout_28[6]}]
set_load -pin_load 0.2 [get_ports {dout_28[5]}]
set_load -pin_load 0.2 [get_ports {dout_28[4]}]
set_load -pin_load 0.2 [get_ports {dout_28[3]}]
set_load -pin_load 0.2 [get_ports {dout_28[2]}]
set_load -pin_load 0.2 [get_ports {dout_28[1]}]
set_load -pin_load 0.2 [get_ports {dout_28[0]}]
set_load -pin_load 0.2 [get_ports {dout_29[7]}]
set_load -pin_load 0.2 [get_ports {dout_29[6]}]
set_load -pin_load 0.2 [get_ports {dout_29[5]}]
set_load -pin_load 0.2 [get_ports {dout_29[4]}]
set_load -pin_load 0.2 [get_ports {dout_29[3]}]
set_load -pin_load 0.2 [get_ports {dout_29[2]}]
set_load -pin_load 0.2 [get_ports {dout_29[1]}]
set_load -pin_load 0.2 [get_ports {dout_29[0]}]
set_load -pin_load 0.2 [get_ports {dout_30[7]}]
set_load -pin_load 0.2 [get_ports {dout_30[6]}]
set_load -pin_load 0.2 [get_ports {dout_30[5]}]
set_load -pin_load 0.2 [get_ports {dout_30[4]}]
set_load -pin_load 0.2 [get_ports {dout_30[3]}]
set_load -pin_load 0.2 [get_ports {dout_30[2]}]
set_load -pin_load 0.2 [get_ports {dout_30[1]}]
set_load -pin_load 0.2 [get_ports {dout_30[0]}]
set_load -pin_load 0.2 [get_ports {dout_31[7]}]
set_load -pin_load 0.2 [get_ports {dout_31[6]}]
set_load -pin_load 0.2 [get_ports {dout_31[5]}]
set_load -pin_load 0.2 [get_ports {dout_31[4]}]
set_load -pin_load 0.2 [get_ports {dout_31[3]}]
set_load -pin_load 0.2 [get_ports {dout_31[2]}]
set_load -pin_load 0.2 [get_ports {dout_31[1]}]
set_load -pin_load 0.2 [get_ports {dout_31[0]}]
set_ideal_network -no_propagate  [get_ports rst_n]
create_clock [get_ports clk]  -period 9.5  -waveform {0 4.75}
set_clock_latency -max 0.95  [get_clocks clk]
set_clock_latency -source 0.95  [get_clocks clk]
set_clock_uncertainty 0.475  [get_clocks clk]
set_clock_transition -max -rise 0.095 [get_clocks clk]
set_clock_transition -max -fall 0.095 [get_clocks clk]
set_clock_transition -min -rise 0.095 [get_clocks clk]
set_clock_transition -min -fall 0.095 [get_clocks clk]
set_false_path   -from [get_ports rst_n]
set_input_delay -clock clk  -max 3.8  [get_ports rst_n]
set_input_delay -clock clk  -min 0  [get_ports rst_n]
set_input_delay -clock clk  -max 3.8  [get_ports vld_in]
set_input_delay -clock clk  -min 0  [get_ports vld_in]
set_input_delay -clock clk  -max 3.8  [get_ports {din_0[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_0[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_0[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_0[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_0[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_0[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_0[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_0[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_0[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_0[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_0[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_0[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_0[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_0[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_0[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_0[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_1[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_1[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_1[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_1[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_1[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_1[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_1[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_1[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_1[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_1[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_1[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_1[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_1[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_1[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_1[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_1[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_2[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_2[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_2[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_2[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_2[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_2[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_2[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_2[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_2[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_2[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_2[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_2[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_2[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_2[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_2[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_2[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_3[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_3[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_3[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_3[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_3[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_3[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_3[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_3[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_3[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_3[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_3[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_3[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_3[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_3[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_3[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_3[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_4[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_4[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_4[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_4[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_4[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_4[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_4[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_4[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_4[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_4[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_4[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_4[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_4[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_4[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_4[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_4[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_5[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_5[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_5[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_5[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_5[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_5[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_5[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_5[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_5[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_5[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_5[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_5[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_5[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_5[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_5[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_5[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_6[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_6[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_6[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_6[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_6[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_6[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_6[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_6[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_6[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_6[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_6[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_6[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_6[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_6[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_6[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_6[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_7[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_7[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_7[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_7[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_7[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_7[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_7[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_7[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_7[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_7[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_7[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_7[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_7[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_7[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_7[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_7[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_8[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_8[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_8[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_8[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_8[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_8[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_8[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_8[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_8[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_8[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_8[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_8[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_8[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_8[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_8[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_8[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_9[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_9[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_9[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_9[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_9[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_9[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_9[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_9[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_9[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_9[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_9[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_9[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_9[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_9[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_9[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_9[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_10[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_10[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_10[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_10[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_10[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_10[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_10[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_10[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_10[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_10[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_10[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_10[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_10[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_10[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_10[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_10[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_11[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_11[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_11[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_11[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_11[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_11[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_11[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_11[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_11[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_11[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_11[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_11[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_11[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_11[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_11[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_11[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_12[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_12[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_12[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_12[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_12[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_12[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_12[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_12[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_12[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_12[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_12[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_12[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_12[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_12[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_12[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_12[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_13[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_13[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_13[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_13[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_13[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_13[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_13[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_13[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_13[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_13[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_13[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_13[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_13[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_13[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_13[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_13[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_14[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_14[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_14[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_14[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_14[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_14[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_14[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_14[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_14[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_14[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_14[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_14[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_14[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_14[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_14[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_14[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_15[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_15[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_15[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_15[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_15[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_15[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_15[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_15[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_15[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_15[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_15[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_15[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_15[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_15[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_15[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_15[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_16[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_16[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_16[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_16[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_16[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_16[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_16[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_16[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_16[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_16[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_16[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_16[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_16[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_16[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_16[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_16[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_17[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_17[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_17[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_17[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_17[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_17[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_17[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_17[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_17[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_17[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_17[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_17[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_17[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_17[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_17[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_17[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_18[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_18[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_18[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_18[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_18[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_18[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_18[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_18[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_18[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_18[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_18[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_18[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_18[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_18[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_18[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_18[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_19[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_19[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_19[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_19[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_19[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_19[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_19[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_19[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_19[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_19[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_19[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_19[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_19[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_19[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_19[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_19[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_20[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_20[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_20[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_20[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_20[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_20[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_20[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_20[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_20[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_20[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_20[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_20[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_20[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_20[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_20[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_20[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_21[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_21[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_21[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_21[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_21[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_21[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_21[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_21[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_21[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_21[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_21[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_21[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_21[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_21[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_21[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_21[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_22[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_22[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_22[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_22[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_22[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_22[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_22[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_22[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_22[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_22[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_22[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_22[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_22[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_22[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_22[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_22[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_23[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_23[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_23[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_23[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_23[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_23[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_23[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_23[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_23[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_23[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_23[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_23[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_23[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_23[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_23[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_23[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_24[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_24[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_24[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_24[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_24[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_24[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_24[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_24[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_24[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_24[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_24[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_24[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_24[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_24[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_24[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_24[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_25[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_25[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_25[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_25[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_25[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_25[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_25[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_25[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_25[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_25[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_25[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_25[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_25[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_25[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_25[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_25[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_26[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_26[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_26[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_26[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_26[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_26[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_26[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_26[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_26[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_26[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_26[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_26[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_26[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_26[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_26[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_26[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_27[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_27[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_27[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_27[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_27[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_27[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_27[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_27[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_27[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_27[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_27[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_27[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_27[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_27[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_27[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_27[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_28[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_28[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_28[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_28[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_28[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_28[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_28[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_28[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_28[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_28[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_28[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_28[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_28[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_28[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_28[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_28[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_29[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_29[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_29[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_29[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_29[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_29[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_29[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_29[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_29[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_29[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_29[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_29[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_29[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_29[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_29[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_29[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_30[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_30[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_30[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_30[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_30[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_30[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_30[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_30[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_30[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_30[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_30[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_30[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_30[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_30[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_30[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_30[0]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_31[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din_31[7]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_31[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din_31[6]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_31[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din_31[5]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_31[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din_31[4]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_31[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din_31[3]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_31[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din_31[2]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_31[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din_31[1]}]
set_input_delay -clock clk  -max 3.8  [get_ports {din_31[0]}]
set_input_delay -clock clk  -min 0  [get_ports {din_31[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports vld_out]
set_output_delay -clock clk  -min 0  [get_ports vld_out]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_0[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_0[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_0[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_0[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_0[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_0[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_0[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_0[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_0[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_0[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_0[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_0[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_0[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_0[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_0[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_0[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_1[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_1[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_1[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_1[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_1[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_1[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_1[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_1[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_1[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_1[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_1[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_1[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_1[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_1[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_1[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_1[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_2[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_2[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_2[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_2[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_2[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_2[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_2[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_2[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_2[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_2[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_2[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_2[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_2[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_2[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_2[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_2[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_3[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_3[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_3[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_3[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_3[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_3[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_3[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_3[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_3[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_3[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_3[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_3[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_3[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_3[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_3[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_3[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_4[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_4[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_4[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_4[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_4[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_4[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_4[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_4[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_4[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_4[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_4[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_4[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_4[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_4[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_4[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_4[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_5[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_5[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_5[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_5[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_5[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_5[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_5[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_5[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_5[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_5[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_5[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_5[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_5[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_5[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_5[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_5[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_6[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_6[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_6[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_6[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_6[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_6[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_6[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_6[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_6[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_6[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_6[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_6[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_6[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_6[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_6[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_6[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_7[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_7[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_7[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_7[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_7[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_7[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_7[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_7[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_7[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_7[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_7[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_7[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_7[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_7[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_7[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_7[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_8[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_8[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_8[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_8[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_8[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_8[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_8[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_8[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_8[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_8[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_8[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_8[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_8[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_8[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_8[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_8[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_9[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_9[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_9[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_9[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_9[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_9[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_9[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_9[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_9[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_9[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_9[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_9[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_9[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_9[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_9[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_9[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_10[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_10[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_10[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_10[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_10[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_10[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_10[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_10[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_10[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_10[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_10[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_10[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_10[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_10[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_10[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_10[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_11[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_11[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_11[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_11[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_11[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_11[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_11[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_11[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_11[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_11[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_11[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_11[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_11[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_11[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_11[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_11[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_12[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_12[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_12[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_12[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_12[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_12[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_12[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_12[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_12[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_12[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_12[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_12[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_12[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_12[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_12[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_12[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_13[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_13[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_13[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_13[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_13[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_13[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_13[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_13[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_13[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_13[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_13[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_13[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_13[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_13[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_13[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_13[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_14[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_14[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_14[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_14[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_14[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_14[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_14[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_14[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_14[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_14[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_14[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_14[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_14[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_14[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_14[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_14[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_15[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_15[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_15[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_15[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_15[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_15[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_15[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_15[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_15[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_15[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_15[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_15[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_15[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_15[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_15[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_15[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_16[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_16[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_16[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_16[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_16[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_16[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_16[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_16[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_16[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_16[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_16[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_16[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_16[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_16[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_16[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_16[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_17[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_17[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_17[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_17[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_17[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_17[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_17[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_17[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_17[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_17[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_17[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_17[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_17[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_17[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_17[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_17[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_18[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_18[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_18[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_18[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_18[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_18[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_18[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_18[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_18[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_18[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_18[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_18[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_18[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_18[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_18[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_18[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_19[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_19[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_19[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_19[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_19[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_19[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_19[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_19[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_19[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_19[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_19[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_19[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_19[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_19[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_19[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_19[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_20[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_20[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_20[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_20[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_20[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_20[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_20[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_20[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_20[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_20[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_20[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_20[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_20[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_20[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_20[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_20[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_21[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_21[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_21[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_21[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_21[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_21[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_21[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_21[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_21[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_21[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_21[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_21[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_21[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_21[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_21[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_21[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_22[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_22[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_22[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_22[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_22[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_22[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_22[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_22[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_22[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_22[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_22[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_22[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_22[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_22[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_22[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_22[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_23[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_23[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_23[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_23[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_23[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_23[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_23[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_23[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_23[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_23[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_23[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_23[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_23[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_23[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_23[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_23[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_24[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_24[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_24[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_24[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_24[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_24[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_24[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_24[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_24[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_24[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_24[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_24[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_24[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_24[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_24[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_24[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_25[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_25[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_25[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_25[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_25[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_25[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_25[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_25[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_25[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_25[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_25[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_25[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_25[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_25[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_25[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_25[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_26[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_26[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_26[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_26[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_26[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_26[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_26[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_26[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_26[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_26[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_26[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_26[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_26[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_26[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_26[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_26[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_27[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_27[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_27[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_27[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_27[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_27[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_27[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_27[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_27[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_27[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_27[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_27[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_27[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_27[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_27[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_27[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_28[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_28[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_28[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_28[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_28[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_28[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_28[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_28[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_28[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_28[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_28[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_28[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_28[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_28[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_28[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_28[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_29[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_29[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_29[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_29[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_29[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_29[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_29[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_29[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_29[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_29[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_29[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_29[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_29[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_29[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_29[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_29[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_30[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_30[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_30[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_30[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_30[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_30[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_30[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_30[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_30[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_30[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_30[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_30[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_30[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_30[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_30[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_30[0]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_31[7]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_31[7]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_31[6]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_31[6]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_31[5]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_31[5]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_31[4]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_31[4]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_31[3]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_31[3]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_31[2]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_31[2]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_31[1]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_31[1]}]
set_output_delay -clock clk  -max 3.8  [get_ports {dout_31[0]}]
set_output_delay -clock clk  -min 0  [get_ports {dout_31[0]}]
